/*
 * Copyright (C) 2020 Andrea Binello ("andbin")
 *
 * This file is part of the "Kotlin+SpringBoot Color Tools" project
 * and is released under the MIT License. See one of the license files
 * included in the root of the project for the full text of the license.
 */

package it.andbin.colortools.model.css

import it.andbin.colortools.model.Color
import it.andbin.colortools.model.ColorPalette

// names-values taken from https://developer.mozilla.org/en-US/docs/Web/CSS/color_value

val cssLevel1Colors = ColorPalette.builder("CSS Level 1") {
    +Color.of("black"  , 0x000000)
    +Color.of("silver" , 0xC0C0C0)
    +Color.of("gray"   , 0x808080)
    +Color.of("white"  , 0xFFFFFF)
    +Color.of("maroon" , 0x800000)
    +Color.of("red"    , 0xFF0000)
    +Color.of("purple" , 0x800080)
    +Color.of("fuchsia", 0xFF00FF)
    +Color.of("green"  , 0x008000)
    +Color.of("lime"   , 0x00FF00)
    +Color.of("olive"  , 0x808000)
    +Color.of("yellow" , 0xFFFF00)
    +Color.of("navy"   , 0x000080)
    +Color.of("blue"   , 0x0000FF)
    +Color.of("teal"   , 0x008080)
    +Color.of("aqua"   , 0x00FFFF)
}

val cssLevel2Rev1Colors = ColorPalette.builder("CSS Level 2 (Revision 1)") {
    +cssLevel1Colors
    +Color.of("orange", 0xFFA500)
}

val cssColorModuleLevel3Colors = ColorPalette.builder("CSS Color Module Level 3") {
    +cssLevel2Rev1Colors
    +Color.of("aliceblue"           , 0xF0F8FF)
    +Color.of("antiquewhite"        , 0xFAEBD7)
    +Color.of("aquamarine"          , 0x7FFFD4)
    +Color.of("azure"               , 0xF0FFFF)
    +Color.of("beige"               , 0xF5F5DC)
    +Color.of("bisque"              , 0xFFE4C4)
    +Color.of("blanchedalmond"      , 0xFFEBCD)
    +Color.of("blueviolet"          , 0x8A2BE2)
    +Color.of("brown"               , 0xA52A2A)
    +Color.of("burlywood"           , 0xDEB887)
    +Color.of("cadetblue"           , 0x5F9EA0)
    +Color.of("chartreuse"          , 0x7FFF00)
    +Color.of("chocolate"           , 0xD2691E)
    +Color.of("coral"               , 0xFF7F50)
    +Color.of("cornflowerblue"      , 0x6495ED)
    +Color.of("cornsilk"            , 0xFFF8DC)
    +Color.of("crimson"             , 0xDC143C)
    +Color.of("cyan"                , 0x00FFFF)
    +Color.of("darkblue"            , 0x00008B)
    +Color.of("darkcyan"            , 0x008B8B)
    +Color.of("darkgoldenrod"       , 0xB8860B)
    +Color.of("darkgray"            , 0xA9A9A9)
    +Color.of("darkgreen"           , 0x006400)
    +Color.of("darkgrey"            , 0xA9A9A9)
    +Color.of("darkkhaki"           , 0xBDB76B)
    +Color.of("darkmagenta"         , 0x8B008B)
    +Color.of("darkolivegreen"      , 0x556B2F)
    +Color.of("darkorange"          , 0xFF8C00)
    +Color.of("darkorchid"          , 0x9932CC)
    +Color.of("darkred"             , 0x8B0000)
    +Color.of("darksalmon"          , 0xE9967A)
    +Color.of("darkseagreen"        , 0x8FBC8F)
    +Color.of("darkslateblue"       , 0x483D8B)
    +Color.of("darkslategray"       , 0x2F4F4F)
    +Color.of("darkslategrey"       , 0x2F4F4F)
    +Color.of("darkturquoise"       , 0x00CED1)
    +Color.of("darkviolet"          , 0x9400D3)
    +Color.of("deeppink"            , 0xFF1493)
    +Color.of("deepskyblue"         , 0x00BFFF)
    +Color.of("dimgray"             , 0x696969)
    +Color.of("dimgrey"             , 0x696969)
    +Color.of("dodgerblue"          , 0x1E90FF)
    +Color.of("firebrick"           , 0xB22222)
    +Color.of("floralwhite"         , 0xFFFAF0)
    +Color.of("forestgreen"         , 0x228B22)
    +Color.of("gainsboro"           , 0xDCDCDC)
    +Color.of("ghostwhite"          , 0xF8F8FF)
    +Color.of("gold"                , 0xFFD700)
    +Color.of("goldenrod"           , 0xDAA520)
    +Color.of("greenyellow"         , 0xADFF2F)
    +Color.of("grey"                , 0x808080)
    +Color.of("honeydew"            , 0xF0FFF0)
    +Color.of("hotpink"             , 0xFF69B4)
    +Color.of("indianred"           , 0xCD5C5C)
    +Color.of("indigo"              , 0x4B0082)
    +Color.of("ivory"               , 0xFFFFF0)
    +Color.of("khaki"               , 0xF0E68C)
    +Color.of("lavender"            , 0xE6E6FA)
    +Color.of("lavenderblush"       , 0xFFF0F5)
    +Color.of("lawngreen"           , 0x7CFC00)
    +Color.of("lemonchiffon"        , 0xFFFACD)
    +Color.of("lightblue"           , 0xADD8E6)
    +Color.of("lightcoral"          , 0xF08080)
    +Color.of("lightcyan"           , 0xE0FFFF)
    +Color.of("lightgoldenrodyellow", 0xFAFAD2)
    +Color.of("lightgray"           , 0xD3D3D3)
    +Color.of("lightgreen"          , 0x90EE90)
    +Color.of("lightgrey"           , 0xD3D3D3)
    +Color.of("lightpink"           , 0xFFB6C1)
    +Color.of("lightsalmon"         , 0xFFA07A)
    +Color.of("lightseagreen"       , 0x20B2AA)
    +Color.of("lightskyblue"        , 0x87CEFA)
    +Color.of("lightslategray"      , 0x778899)
    +Color.of("lightslategrey"      , 0x778899)
    +Color.of("lightsteelblue"      , 0xB0C4DE)
    +Color.of("lightyellow"         , 0xFFFFE0)
    +Color.of("limegreen"           , 0x32CD32)
    +Color.of("linen"               , 0xFAF0E6)
    +Color.of("magenta"             , 0xFF00FF)
    +Color.of("mediumaquamarine"    , 0x66CDAA)
    +Color.of("mediumblue"          , 0x0000CD)
    +Color.of("mediumorchid"        , 0xBA55D3)
    +Color.of("mediumpurple"        , 0x9370DB)
    +Color.of("mediumseagreen"      , 0x3CB371)
    +Color.of("mediumslateblue"     , 0x7B68EE)
    +Color.of("mediumspringgreen"   , 0x00FA9A)
    +Color.of("mediumturquoise"     , 0x48D1CC)
    +Color.of("mediumvioletred"     , 0xC71585)
    +Color.of("midnightblue"        , 0x191970)
    +Color.of("mintcream"           , 0xF5FFFA)
    +Color.of("mistyrose"           , 0xFFE4E1)
    +Color.of("moccasin"            , 0xFFE4B5)
    +Color.of("navajowhite"         , 0xFFDEAD)
    +Color.of("oldlace"             , 0xFDF5E6)
    +Color.of("olivedrab"           , 0x6B8E23)
    +Color.of("orangered"           , 0xFF4500)
    +Color.of("orchid"              , 0xDA70D6)
    +Color.of("palegoldenrod"       , 0xEEE8AA)
    +Color.of("palegreen"           , 0x98FB98)
    +Color.of("paleturquoise"       , 0xAFEEEE)
    +Color.of("palevioletred"       , 0xDB7093)
    +Color.of("papayawhip"          , 0xFFEFD5)
    +Color.of("peachpuff"           , 0xFFDAB9)
    +Color.of("peru"                , 0xCD853F)
    +Color.of("pink"                , 0xFFC0CB)
    +Color.of("plum"                , 0xDDA0DD)
    +Color.of("powderblue"          , 0xB0E0E6)
    +Color.of("rosybrown"           , 0xBC8F8F)
    +Color.of("royalblue"           , 0x4169E1)
    +Color.of("saddlebrown"         , 0x8B4513)
    +Color.of("salmon"              , 0xFA8072)
    +Color.of("sandybrown"          , 0xF4A460)
    +Color.of("seagreen"            , 0x2E8B57)
    +Color.of("seashell"            , 0xFFF5EE)
    +Color.of("sienna"              , 0xA0522D)
    +Color.of("skyblue"             , 0x87CEEB)
    +Color.of("slateblue"           , 0x6A5ACD)
    +Color.of("slategray"           , 0x708090)
    +Color.of("slategrey"           , 0x708090)
    +Color.of("snow"                , 0xFFFAFA)
    +Color.of("springgreen"         , 0x00FF7F)
    +Color.of("steelblue"           , 0x4682B4)
    +Color.of("tan"                 , 0xD2B48C)
    +Color.of("thistle"             , 0xD8BFD8)
    +Color.of("tomato"              , 0xFF6347)
    +Color.of("turquoise"           , 0x40E0D0)
    +Color.of("violet"              , 0xEE82EE)
    +Color.of("wheat"               , 0xF5DEB3)
    +Color.of("whitesmoke"          , 0xF5F5F5)
    +Color.of("yellowgreen"         , 0x9ACD32)
}

val cssColorModuleLevel4Colors = ColorPalette.builder("CSS Color Module Level 4") {
    +cssColorModuleLevel3Colors
    +Color.of("rebeccapurple", 0x663399)
}
