/*
 * Copyright (C) 2020 Andrea Binello ("andbin")
 *
 * This file is part of the "Kotlin+SpringBoot Color Tools" project
 * and is released under the MIT License. See one of the license files
 * included in the root of the project for the full text of the license.
 */

package it.andbin.colortools.model.css

import it.andbin.colortools.model.Color
import it.andbin.colortools.model.ColorPalette

// names and values taken from https://developer.mozilla.org/en-US/docs/Web/CSS/color_value

val cssLevel1Colors = ColorPalette.builder("CSS Level 1") {
    +Color.of(0x000000, "black")
    +Color.of(0xC0C0C0, "silver")
    +Color.of(0x808080, "gray")
    +Color.of(0xFFFFFF, "white")
    +Color.of(0x800000, "maroon")
    +Color.of(0xFF0000, "red")
    +Color.of(0x800080, "purple")
    +Color.of(0xFF00FF, "fuchsia")
    +Color.of(0x008000, "green")
    +Color.of(0x00FF00, "lime")
    +Color.of(0x808000, "olive")
    +Color.of(0xFFFF00, "yellow")
    +Color.of(0x000080, "navy")
    +Color.of(0x0000FF, "blue")
    +Color.of(0x008080, "teal")
    +Color.of(0x00FFFF, "aqua")
}

val cssLevel2Rev1Colors = ColorPalette.builder("CSS Level 2 (Revision 1)") {
    +cssLevel1Colors
    +Color.of(0xFFA500, "orange")
}

val cssColorModuleLevel3Colors = ColorPalette.builder("CSS Color Module Level 3") {
    +cssLevel2Rev1Colors
    +Color.of(0xF0F8FF, "aliceblue")
    +Color.of(0xFAEBD7, "antiquewhite")
    +Color.of(0x7FFFD4, "aquamarine")
    +Color.of(0xF0FFFF, "azure")
    +Color.of(0xF5F5DC, "beige")
    +Color.of(0xFFE4C4, "bisque")
    +Color.of(0xFFEBCD, "blanchedalmond")
    +Color.of(0x8A2BE2, "blueviolet")
    +Color.of(0xA52A2A, "brown")
    +Color.of(0xDEB887, "burlywood")
    +Color.of(0x5F9EA0, "cadetblue")
    +Color.of(0x7FFF00, "chartreuse")
    +Color.of(0xD2691E, "chocolate")
    +Color.of(0xFF7F50, "coral")
    +Color.of(0x6495ED, "cornflowerblue")
    +Color.of(0xFFF8DC, "cornsilk")
    +Color.of(0xDC143C, "crimson")
    +Color.of(0x00FFFF, "cyan")
    +Color.of(0x00008B, "darkblue")
    +Color.of(0x008B8B, "darkcyan")
    +Color.of(0xB8860B, "darkgoldenrod")
    +Color.of(0xA9A9A9, "darkgray")
    +Color.of(0x006400, "darkgreen")
    +Color.of(0xA9A9A9, "darkgrey")
    +Color.of(0xBDB76B, "darkkhaki")
    +Color.of(0x8B008B, "darkmagenta")
    +Color.of(0x556B2F, "darkolivegreen")
    +Color.of(0xFF8C00, "darkorange")
    +Color.of(0x9932CC, "darkorchid")
    +Color.of(0x8B0000, "darkred")
    +Color.of(0xE9967A, "darksalmon")
    +Color.of(0x8FBC8F, "darkseagreen")
    +Color.of(0x483D8B, "darkslateblue")
    +Color.of(0x2F4F4F, "darkslategray")
    +Color.of(0x2F4F4F, "darkslategrey")
    +Color.of(0x00CED1, "darkturquoise")
    +Color.of(0x9400D3, "darkviolet")
    +Color.of(0xFF1493, "deeppink")
    +Color.of(0x00BFFF, "deepskyblue")
    +Color.of(0x696969, "dimgray")
    +Color.of(0x696969, "dimgrey")
    +Color.of(0x1E90FF, "dodgerblue")
    +Color.of(0xB22222, "firebrick")
    +Color.of(0xFFFAF0, "floralwhite")
    +Color.of(0x228B22, "forestgreen")
    +Color.of(0xDCDCDC, "gainsboro")
    +Color.of(0xF8F8FF, "ghostwhite")
    +Color.of(0xFFD700, "gold")
    +Color.of(0xDAA520, "goldenrod")
    +Color.of(0xADFF2F, "greenyellow")
    +Color.of(0x808080, "grey")
    +Color.of(0xF0FFF0, "honeydew")
    +Color.of(0xFF69B4, "hotpink")
    +Color.of(0xCD5C5C, "indianred")
    +Color.of(0x4B0082, "indigo")
    +Color.of(0xFFFFF0, "ivory")
    +Color.of(0xF0E68C, "khaki")
    +Color.of(0xE6E6FA, "lavender")
    +Color.of(0xFFF0F5, "lavenderblush")
    +Color.of(0x7CFC00, "lawngreen")
    +Color.of(0xFFFACD, "lemonchiffon")
    +Color.of(0xADD8E6, "lightblue")
    +Color.of(0xF08080, "lightcoral")
    +Color.of(0xE0FFFF, "lightcyan")
    +Color.of(0xFAFAD2, "lightgoldenrodyellow")
    +Color.of(0xD3D3D3, "lightgray")
    +Color.of(0x90EE90, "lightgreen")
    +Color.of(0xD3D3D3, "lightgrey")
    +Color.of(0xFFB6C1, "lightpink")
    +Color.of(0xFFA07A, "lightsalmon")
    +Color.of(0x20B2AA, "lightseagreen")
    +Color.of(0x87CEFA, "lightskyblue")
    +Color.of(0x778899, "lightslategray")
    +Color.of(0x778899, "lightslategrey")
    +Color.of(0xB0C4DE, "lightsteelblue")
    +Color.of(0xFFFFE0, "lightyellow")
    +Color.of(0x32CD32, "limegreen")
    +Color.of(0xFAF0E6, "linen")
    +Color.of(0xFF00FF, "magenta")
    +Color.of(0x66CDAA, "mediumaquamarine")
    +Color.of(0x0000CD, "mediumblue")
    +Color.of(0xBA55D3, "mediumorchid")
    +Color.of(0x9370DB, "mediumpurple")
    +Color.of(0x3CB371, "mediumseagreen")
    +Color.of(0x7B68EE, "mediumslateblue")
    +Color.of(0x00FA9A, "mediumspringgreen")
    +Color.of(0x48D1CC, "mediumturquoise")
    +Color.of(0xC71585, "mediumvioletred")
    +Color.of(0x191970, "midnightblue")
    +Color.of(0xF5FFFA, "mintcream")
    +Color.of(0xFFE4E1, "mistyrose")
    +Color.of(0xFFE4B5, "moccasin")
    +Color.of(0xFFDEAD, "navajowhite")
    +Color.of(0xFDF5E6, "oldlace")
    +Color.of(0x6B8E23, "olivedrab")
    +Color.of(0xFF4500, "orangered")
    +Color.of(0xDA70D6, "orchid")
    +Color.of(0xEEE8AA, "palegoldenrod")
    +Color.of(0x98FB98, "palegreen")
    +Color.of(0xAFEEEE, "paleturquoise")
    +Color.of(0xDB7093, "palevioletred")
    +Color.of(0xFFEFD5, "papayawhip")
    +Color.of(0xFFDAB9, "peachpuff")
    +Color.of(0xCD853F, "peru")
    +Color.of(0xFFC0CB, "pink")
    +Color.of(0xDDA0DD, "plum")
    +Color.of(0xB0E0E6, "powderblue")
    +Color.of(0xBC8F8F, "rosybrown")
    +Color.of(0x4169E1, "royalblue")
    +Color.of(0x8B4513, "saddlebrown")
    +Color.of(0xFA8072, "salmon")
    +Color.of(0xF4A460, "sandybrown")
    +Color.of(0x2E8B57, "seagreen")
    +Color.of(0xFFF5EE, "seashell")
    +Color.of(0xA0522D, "sienna")
    +Color.of(0x87CEEB, "skyblue")
    +Color.of(0x6A5ACD, "slateblue")
    +Color.of(0x708090, "slategray")
    +Color.of(0x708090, "slategrey")
    +Color.of(0xFFFAFA, "snow")
    +Color.of(0x00FF7F, "springgreen")
    +Color.of(0x4682B4, "steelblue")
    +Color.of(0xD2B48C, "tan")
    +Color.of(0xD8BFD8, "thistle")
    +Color.of(0xFF6347, "tomato")
    +Color.of(0x40E0D0, "turquoise")
    +Color.of(0xEE82EE, "violet")
    +Color.of(0xF5DEB3, "wheat")
    +Color.of(0xF5F5F5, "whitesmoke")
    +Color.of(0x9ACD32, "yellowgreen")
}

val cssColorModuleLevel4Colors = ColorPalette.builder("CSS Color Module Level 4") {
    +cssColorModuleLevel3Colors
    +Color.of(0x663399, "rebeccapurple")
}
